import { ImageResponse } from 'next/og';
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';

/**
 * Social card generated by code.
 *
 * Open Graph previously pointed to an 800x800 square logo. WhatsApp, Discord,
 * Twitter, and Telegram crop or shrink square images, making shared links
 * look poor precisely in channels driving traffic to a tool like this.
 * 1200x630 is the aspect ratio expected by all of them.
 *
 * Generated here rather than exporting a PNG so card tracks the product:
 * if headline or supported services change, card updates accordingly.
 */
export const alt = 'SyncSekai — Sync anime from Plex, Jellyfin & Emby to AniList, MyAnimeList & Kitsu';
export const size = { width: 1200, height: 630 };
export const contentType = 'image/png';

/**
 * Fetches a variant of Outfit, the site's own font.
 *
 * Returns null on failure: without custom font the card renders with default
 * typography, which is less ideal but functional. Network outage must not
 * fail the entire build over an image.
 */
async function loadOutfit(peso: number): Promise<ArrayBuffer | null> {
  try {
    const css = await fetch(
      `https://fonts.googleapis.com/css2?family=Outfit:wght@${peso}&display=swap`,
      // Without a browser User-Agent, Google returns woff2, which Satori cannot parse.
      { headers: { 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)' } },
    ).then((r) => r.text());

    const url = css.match(/src:\s*url\((https:[^)]+)\)/)?.[1];
    if (!url) return null;
    return await fetch(url).then((r) => r.arrayBuffer());
  } catch {
    return null;
  }
}

/** Reads an asset from /public and returns it as data URI for embedding. */
async function asDataUri(file: string, mime: string): Promise<string | null> {
  try {
    const bin = await readFile(join(process.cwd(), 'public', file));
    return `data:${mime};base64,${bin.toString('base64')}`;
  } catch {
    return null;
  }
}

export default async function OpengraphImage() {
  const [bold, media, logo, plex, jellyfin, emby, anilist, mal] = await Promise.all([
    loadOutfit(800),
    loadOutfit(500),
    asDataUri('icon.png', 'image/png'),
    asDataUri('plex.svg', 'image/svg+xml'),
    asDataUri('jellyfin.svg', 'image/svg+xml'),
    asDataUri('emby.svg', 'image/svg+xml'),
    asDataUri('anilist.svg', 'image/svg+xml'),
    asDataUri('mal.svg', 'image/svg+xml'),
  ]);

  const fonts = [
    bold && { name: 'Outfit', data: bold, weight: 800 as const, style: 'normal' as const },
    media && { name: 'Outfit', data: media, weight: 500 as const, style: 'normal' as const },
  ].filter(Boolean) as { name: string; data: ArrayBuffer; weight: 800 | 500; style: 'normal' }[];

  const family = fonts.length ? 'Outfit' : undefined;

  // Kitsu has no logo in /public, so it is represented by its brand color.
  // A coherent pill is better than an empty gap or lower-quality logo.
  const services = [
    { name: 'Plex', icon: plex, color: '#E5A00D' },
    { name: 'Jellyfin', icon: jellyfin, color: '#AA5CC3' },
    { name: 'Emby', icon: emby, color: '#52B54B' },
    { name: 'AniList', icon: anilist, color: '#02A9FF' },
    { name: 'MyAnimeList', icon: mal, color: '#2E51A2' },
    { name: 'Kitsu', icon: null, color: '#FD755C' },
  ];

  return new ImageResponse(
    (
      <div
        style={{
          width: '100%',
          height: '100%',
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'space-between',
          padding: '68px 76px',
          background: '#141414',
          backgroundImage:
            'radial-gradient(circle at 12% 6%, rgba(255,99,74,0.30), transparent 42%), radial-gradient(circle at 92% 96%, rgba(2,169,255,0.18), transparent 46%)',
          fontFamily: family,
          color: '#F4F4F6',
        }}
      >
        {/* Marca */}
        <div style={{ display: 'flex', alignItems: 'center', gap: 14 }}>
          {logo ? (
            <img src={logo} width={40} height={40} alt="" style={{ borderRadius: 10 }} />
          ) : (
            <div style={{ width: 40, height: 40, borderRadius: 10, background: '#FF634A', display: 'flex' }} />
          )}
          <div style={{ display: 'flex', fontSize: 32, fontWeight: 800, letterSpacing: '-0.5px' }}>
            SyncSekai
          </div>
          <div
            style={{
              display: 'flex',
              marginLeft: 6,
              padding: '5px 12px',
              borderRadius: 999,
              fontSize: 17,
              fontWeight: 500,
              color: '#A1A1AA',
              border: '1px solid rgba(255,255,255,0.14)',
            }}
          >
            Anime scrobbler
          </div>
        </div>

        {/* Titular */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
          <div
            style={{
              display: 'flex',
              fontSize: 66,
              fontWeight: 800,
              lineHeight: 1.08,
              letterSpacing: '-2.4px',
              maxWidth: 940,
            }}
          >
            Every episode you watch, already on your lists.
          </div>
          <div
            style={{
              display: 'flex',
              fontSize: 27,
              fontWeight: 500,
              color: '#A1A1AA',
              maxWidth: 880,
              lineHeight: 1.35,
            }}
          >
            Plex, Jellyfin and Emby to AniList, MyAnimeList and Kitsu, in real time. Nothing to install.
          </div>
        </div>

        {/* Servicios soportados */}
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          {services.map((s) => (
            <div
              key={s.name}
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: 10,
                padding: '10px 16px',
                borderRadius: 12,
                background: 'rgba(255,255,255,0.05)',
                border: `1px solid ${s.color}55`,
              }}
            >
              {s.icon ? (
                <img src={s.icon} width={24} height={24} alt="" style={{ borderRadius: 5 }} />
              ) : (
                <div
                  style={{ width: 24, height: 24, borderRadius: 5, background: s.color, display: 'flex' }}
                />
              )}
              <div style={{ display: 'flex', fontSize: 21, fontWeight: 500, color: '#E4E4E7' }}>
                {s.name}
              </div>
            </div>
          ))}
        </div>
      </div>
    ),
    { ...size, ...(fonts.length ? { fonts } : {}) },
  );
}
