import type { BannerPreset } from './announcements.service';

/** Announcement templates offered by the panel. */
export const ANNOUNCEMENT_PRESETS: BannerPreset[] = [
  // -------------------------------------------------------------------------
  // CATEGORY: FESTIVE & SEASONS
  // -------------------------------------------------------------------------
  {
    id: 'christmas',
    name: 'Christmas & Winter',
    category: 'FESTIVE',
    themePreset: 'CHRISTMAS',
    badgeText: 'MERRY CHRISTMAS',
    badgeBgColor: '#e53935',
    badgeTextColor: '#ffffff',
    message: 'Celebrate the holidays with your favorite anime! Enjoy the festive atmosphere.',
    mediaType: 'NONE',
    mediaUrl: null,
    mediaPosition: 'LEFT',
    backgroundType: 'GRADIENT',
    backgroundValue: 'linear-gradient(90deg, #1b4332 0%, #2d6a4f 50%, #b7094c 100%)',
    textColor: '#f8f9fa',
    effectType: 'SNOWFLAKES',
    enableGlobalAtmosphere: true,
    ctaText: 'View catalog',
    ctaUrl: '/catalog',
    ctaTarget: '_self',
    ctaBgColor: '#f8f9fa',
    ctaTextColor: '#1b4332',
    isClosable: true,
  },
  {
    id: 'autumn',
    name: 'Golden Autumn & Leaves',
    category: 'FESTIVE',
    themePreset: 'AUTUMN',
    badgeText: 'AUTUMN',
    badgeBgColor: '#d97706',
    badgeTextColor: '#ffffff',
    message: 'Fall premiere season: new simulcast series syncing now.',
    mediaType: 'NONE',
    mediaUrl: null,
    mediaPosition: 'LEFT',
    backgroundType: 'GRADIENT',
    backgroundValue: 'linear-gradient(90deg, #451a03 0%, #9a3412 50%, #b45309 100%)',
    textColor: '#fffbeb',
    effectType: 'AUTUMN_LEAVES',
    enableGlobalAtmosphere: true,
    ctaText: 'Fall premieres',
    ctaUrl: '/catalog',
    ctaTarget: '_self',
    ctaBgColor: '#fef3c7',
    ctaTextColor: '#78350f',
    isClosable: true,
  },
  {
    id: 'valentine',
    name: 'Valentine\'s Day',
    category: 'FESTIVE',
    themePreset: 'VALENTINE',
    badgeText: 'VALENTINE\'S DAY',
    badgeBgColor: '#ff2a6d',
    badgeTextColor: '#ffffff',
    message: 'Share your passion for anime! Sync episodes with your other half.',
    mediaType: 'NONE',
    mediaUrl: null,
    mediaPosition: 'LEFT',
    backgroundType: 'GRADIENT',
    backgroundValue: 'linear-gradient(90deg, #833ab4 0%, #fd1d1d 50%, #fcb045 100%)',
    textColor: '#ffffff',
    effectType: 'FLOATING_HEARTS',
    enableGlobalAtmosphere: true,
    ctaText: 'My mappings',
    ctaUrl: '/mappings',
    ctaTarget: '_self',
    ctaBgColor: '#ffffff',
    ctaTextColor: '#d81159',
    isClosable: true,
  },
  {
    id: 'halloween',
    name: 'Halloween',
    category: 'FESTIVE',
    themePreset: 'HALLOWEEN',
    badgeText: 'HALLOWEEN',
    badgeBgColor: '#ff6b35',
    badgeTextColor: '#1b1b1b',
    message: 'Horror marathon night: discover the best suspense and horror series.',
    mediaType: 'NONE',
    mediaUrl: null,
    mediaPosition: 'LEFT',
    backgroundType: 'GRADIENT',
    backgroundValue: 'linear-gradient(90deg, #1a0826 0%, #4a154b 50%, #e85d04 100%)',
    textColor: '#f9f9f9',
    effectType: 'SPOOKY_BATS',
    enableGlobalAtmosphere: true,
    ctaText: 'View history',
    ctaUrl: '/history',
    ctaTarget: '_self',
    ctaBgColor: '#ff6b35',
    ctaTextColor: '#000000',
    isClosable: true,
  },
  {
    id: 'new_year',
    name: 'New Year',
    category: 'FESTIVE',
    themePreset: 'NEW_YEAR',
    badgeText: 'HAPPY NEW YEAR!',
    badgeBgColor: '#ffd700',
    badgeTextColor: '#1a1a1a',
    message: 'Start the new year with all your anime and progress in sync!',
    mediaType: 'NONE',
    mediaUrl: null,
    mediaPosition: 'LEFT',
    backgroundType: 'GRADIENT',
    backgroundValue: 'linear-gradient(90deg, #0f2027 0%, #203a43 50%, #2c5364 100%)',
    textColor: '#ffffff',
    effectType: 'FIREWORKS',
    enableGlobalAtmosphere: true,
    ctaText: 'Explore premieres',
    ctaUrl: '/catalog',
    ctaTarget: '_self',
    ctaBgColor: '#ffd700',
    ctaTextColor: '#1a1a1a',
    isClosable: true,
  },

  // -------------------------------------------------------------------------
  // CATEGORY: PROMOTIONS & OFFERS
  // -------------------------------------------------------------------------
  {
    id: 'mee6_promo',
    name: 'Promotions & Discounts',
    category: 'PROMO',
    themePreset: 'MEE6_PROMO',
    badgeText: '50% OFF',
    badgeBgColor: '#ff4d4f',
    badgeTextColor: '#ffffff',
    message: 'Level Up For Less ... Get 50% off SyncSekai Premium!',
    mediaType: 'NONE',
    mediaUrl: null,
    mediaPosition: 'LEFT',
    backgroundType: 'GRADIENT',
    backgroundValue: 'linear-gradient(90deg, #0ba360 0%, #3cba92 100%)',
    textColor: '#ffffff',
    effectType: 'SPARKLES',
    enableGlobalAtmosphere: false,
    ctaText: 'UPGRADE NOW',
    ctaUrl: '/connections',
    ctaTarget: '_self',
    ctaBgColor: '#ffffff',
    ctaTextColor: '#0ba360',
    isClosable: true,
  },
  {
    id: 'mee6_sky',
    name: 'Anime Sky',
    category: 'PROMO',
    themePreset: 'MEE6_SKY',
    badgeText: 'NEW',
    badgeBgColor: '#ff4d4f',
    badgeTextColor: '#ffffff',
    message: 'Exact real-time sync with AniList & MyAnimeList is active.',
    mediaType: 'NONE',
    mediaUrl: null,
    mediaPosition: 'LEFT',
    backgroundType: 'GRADIENT',
    backgroundValue: 'linear-gradient(90deg, #00c6ff 0%, #0072ff 100%)',
    textColor: '#ffffff',
    effectType: 'SPARKLES',
    enableGlobalAtmosphere: false,
    ctaText: 'EXPLORE HUB',
    ctaUrl: '/connections',
    ctaTarget: '_self',
    ctaBgColor: '#ffffff',
    ctaTextColor: '#0072ff',
    isClosable: true,
  },
  {
    id: 'cyber_neon',
    name: 'Cyberpunk / Electric Neon',
    category: 'PROMO',
    themePreset: 'CYBER_NEON',
    badgeText: 'NEON ENGINE',
    badgeBgColor: '#00f0ff',
    badgeTextColor: '#000000',
    message: 'Plex scrobble engine v2.4 active with native ultra-low latency support.',
    mediaType: 'NONE',
    mediaUrl: null,
    mediaPosition: 'LEFT',
    backgroundType: 'GRADIENT',
    backgroundValue: 'linear-gradient(90deg, #050505 0%, #001f3f 50%, #00f0ff 100%)',
    textColor: '#ffffff',
    effectType: 'CYBER_GLOW',
    enableGlobalAtmosphere: false,
    ctaText: 'Diagnostics',
    ctaUrl: '/admin/services',
    ctaTarget: '_self',
    ctaBgColor: '#00f0ff',
    ctaTextColor: '#000000',
    isClosable: true,
  },

  // -------------------------------------------------------------------------
  // CATEGORY: INFORMATIONAL & STATUS
  // -------------------------------------------------------------------------
  {
    id: 'info_notice',
    name: 'Information notice',
    category: 'INFO',
    themePreset: 'INFO',
    badgeText: 'ANNOUNCEMENT',
    badgeBgColor: '#3b82f6',
    badgeTextColor: '#ffffff',
    message: 'System update complete. All integrations are working normally.',
    mediaType: 'NONE',
    mediaUrl: null,
    mediaPosition: 'LEFT',
    backgroundType: 'GRADIENT',
    backgroundValue: 'linear-gradient(90deg, #1e293b 0%, #0f172a 100%)',
    textColor: '#e2e8f0',
    effectType: 'NONE',
    enableGlobalAtmosphere: false,
    ctaText: 'Documentation',
    ctaUrl: '/docs',
    ctaTarget: '_self',
    ctaBgColor: '#38bdf8',
    ctaTextColor: '#0f172a',
    isClosable: true,
  },
  {
    id: 'warning_maintenance',
    name: 'Scheduled maintenance',
    category: 'INFO',
    themePreset: 'WARNING',
    badgeText: 'MAINTENANCE',
    badgeBgColor: '#f59e0b',
    badgeTextColor: '#000000',
    message: 'Scheduled maintenance window for optimization and index sync.',
    mediaType: 'NONE',
    mediaUrl: null,
    mediaPosition: 'LEFT',
    backgroundType: 'GRADIENT',
    backgroundValue: 'linear-gradient(90deg, #451a03 0%, #78350f 100%)',
    textColor: '#fef3c7',
    effectType: 'NONE',
    enableGlobalAtmosphere: false,
    ctaText: 'Node status',
    ctaUrl: '/admin/services',
    ctaTarget: '_self',
    ctaBgColor: '#fbbf24',
    ctaTextColor: '#451a03',
    isClosable: false,
  },
  {
    id: 'domain_migration_syncsekai',
    name: 'Domain migration to SyncSekai',
    category: 'INFO',
    themePreset: 'INFO',
    badgeText: 'NEW DOMAIN',
    badgeBgColor: '#3b82f6',
    badgeTextColor: '#ffffff',
    message: 'We are moving to syncsekai.com. This site will keep working here during the transition, but update your webhook URLs to syncsekai.com before the stated deadline so you do not lose sync when we complete the domain change.',
    mediaType: 'NONE',
    mediaUrl: null,
    mediaPosition: 'LEFT',
    backgroundType: 'GRADIENT',
    backgroundValue: 'linear-gradient(90deg, #1e293b 0%, #0f172a 100%)',
    textColor: '#e2e8f0',
    effectType: 'NONE',
    enableGlobalAtmosphere: false,
    ctaText: 'View the webhooks guide',
    ctaUrl: '/docs',
    ctaTarget: '_self',
    ctaBgColor: '#38bdf8',
    ctaTextColor: '#0f172a',
    isClosable: true,
  },
  {
    id: 'critical_alert',
    name: 'Critical alert / Incident',
    category: 'INFO',
    themePreset: 'CRITICAL',
    badgeText: 'CRITICAL ALERT',
    badgeBgColor: '#ef4444',
    badgeTextColor: '#ffffff',
    message: 'Temporary outage in the remote metadata API. We are investigating the cause.',
    mediaType: 'NONE',
    mediaUrl: null,
    mediaPosition: 'LEFT',
    backgroundType: 'GRADIENT',
    backgroundValue: 'linear-gradient(90deg, #450a0a 0%, #7f1d1d 100%)',
    textColor: '#fee2e2',
    effectType: 'NONE',
    enableGlobalAtmosphere: false,
    ctaText: 'Ver Logs',
    ctaUrl: '/admin/logs',
    ctaTarget: '_self',
    ctaBgColor: '#ef4444',
    ctaTextColor: '#ffffff',
    isClosable: true,
  },
];
